In [1]:
import pandas as pd
import numpy as np
from random import sample
from pandas import *
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

# Libraries from Alan
from __future__ import division
import json
import os
from matplotlib.pyplot import *

import requests
#import tmy_ids

# Show Plots in the Notebook
%matplotlib inline

# Make Plots larger
rcParams['figure.figsize']= (10, 6)
rcParams['font.size'] = 14

%matplotlib inline

print 'Pandas version: ' + pd.__version__

Pandas version: 0.14.0

In [5]:
offsets = pd.read_csv(r"C:\Users\dustin\Documents\IPython Notebooks\City_Weather_Offsets_From_Ian.csv", header=0)
list(offsets.columns.values)

['City_Name',
 'ID',
 'Place',
 'Elevation',
 'Latitude',
 'Longitude',
 'Station_Name',
 'Station_Code',
 'Miles_Away',
 'Temp_Annual',
 'Temp_1',
 'Temp_2',
 'Temp_3',
 'Temp_4',
 'Temp_5',
 'Temp_6',
 'Temp_7',
 'Temp_8',
 'Temp_9',
 'Temp_10',
 'Temp_11',
 'Temp_12',
 'Wind_Speed',
 'Solar_Annual',
 'Solar_1',
 'Solar_2',
 'Solar_3',
 'Solar_4',
 'Solar_5',
 'Solar_6',
 'Solar_7',
 'Solar_8',
 'Solar_9',
 'Solar_10',
 'Solar_11',
 'Solar_12']

In [26]:
subset = offsets[['City_Name', 'Temp_1',
 'Temp_2',
 'Temp_3',
 'Temp_4',
 'Temp_5',
 'Temp_6',
 'Temp_7',
 'Temp_8',
 'Temp_9',
 'Temp_10',
 'Temp_11',
 'Temp_12']]

solar_subset = offsets[['City_Name', 'Solar_1',
 'Solar_2',
 'Solar_3',
 'Solar_4',
 'Solar_5',
 'Solar_6',
 'Solar_7',
 'Solar_8',
 'Solar_9',
 'Solar_10',
 'Solar_11',
 'Solar_12']]

In [27]:
subset.head()

,City_Name,Temp_1,Temp_2,Temp_3,Temp_4,Temp_5,Temp_6,Temp_7,Temp_8,Temp_9,Temp_10,Temp_11,Temp_12
0,Adak,2.8,3.1,0.5,1.0,-1.3,-1.7,-2.5,-2.6,-0.9,0.7,2.1,3.8
1,Akhiok,0.3,-0.1,-0.1,0.5,-0.6,-0.1,-0.6,-1.0,0.4,0.5,0.5,1.7
2,Akiachak,0.1,-0.1,-0.2,0.2,0.1,0.2,0.2,0.2,0.2,0.2,0.0,-0.1
3,Akiak,0.2,0.0,-0.1,0.2,0.0,0.1,0.1,0.1,0.2,0.2,0.0,-0.2
4,Akutan,-1.9,-1.8,-2.2,-1.4,-0.7,0.1,-0.4,-1.1,-1.0,-0.8,-2.1,-1.7

In [28]:
results = pd.DataFrame()
monthly_offsets = pd.DataFrame()
for x in range(1,13):
    results['City_Name'] = subset[['City_Name']]
    results['Temp_offset'] = subset[subset.columns[x]]
    results['month'] = x
    monthly_offsets = monthly_offsets.append(results)

In [29]:
sorted_offsets = monthly_offsets.sort(columns=['City_Name', 'month'])
sorted_offsets

    City_Name  Temp_offset  month
0        Adak          2.8      1
0        Adak          3.1      2
0        Adak          0.5      3
0        Adak          1.0      4
0        Adak         -1.3      5
0        Adak         -1.7      6
0        Adak         -2.5      7
0        Adak         -2.6      8
0        Adak         -0.9      9
0        Adak          0.7     10
0        Adak          2.1     11
0        Adak          3.8     12
1      Akhiok          0.3      1
1      Akhiok         -0.1      2
1      Akhiok         -0.1      3
1      Akhiok          0.5      4
1      Akhiok         -0.6      5
1      Akhiok         -0.1      6
1      Akhiok         -0.6      7
1      Akhiok         -1.0      8
1      Akhiok          0.4      9
1      Akhiok          0.5     10
1      Akhiok          0.5     11
1      Akhiok          1.7     12
2    Akiachak          0.1      1
2    Akiachak         -0.1      2
2    Akiachak         -0.2      3
2    Akiachak          0.2      4
2    Akiachak          0.1      5
2    Akiachak          0.2      6
..        ...          ...    ...
272   Wiseman         -2.0      7
272   Wiseman         -1.9      8
272   Wiseman         -1.6      9
272   Wiseman         -0.9     10
272   Wiseman          0.8     11
272   Wiseman          3.5     12
273  Wrangell         -0.6      1
273  Wrangell         -0.5      2
273  Wrangell         -0.6      3
273  Wrangell         -0.6      4
273  Wrangell         -0.1      5
273  Wrangell          0.2      6
273  Wrangell          0.0      7
273  Wrangell         -0.1      8
273  Wrangell         -0.2      9
273  Wrangell         -0.4     10
273  Wrangell         -0.6     11
273  Wrangell         -0.6     12
274   Yakutat          0.1      1
274   Yakutat          0.0      2
274   Yakutat          0.0      3
274   Yakutat         -0.1      4
274   Yakutat          0.0      5
274   Yakutat         -0.1      6
274   Yakutat         -0.2      7
274   Yakutat         -0.1      8
274   Yakutat          0.0      9
274   Yakutat         -0.1     10
274   Yakutat          0.0     11
274   Yakutat          0.0     12

[3300 rows x 3 columns]

In [30]:
results = pd.DataFrame()
solar_offsets = pd.DataFrame()
for x in range(1,13):
    results['City_Name'] = solar_subset[['City_Name']]
    results['solar_offset'] = solar_subset[solar_subset.columns[x]]
    results['month'] = x
    solar_offsets = solar_offsets.append(results)
    
sorted_solar = solar_offsets.sort(columns=['City_Name', 'month'])
sorted_solar

    City_Name  solar_offset  month
0        Adak          1.23      1
0        Adak          1.13      2
0        Adak          0.87      3
0        Adak          1.00      4
0        Adak          0.95      5
0        Adak          0.90      6
0        Adak          0.80      7
0        Adak          0.90      8
0        Adak          1.11      9
0        Adak          1.21     10
0        Adak          1.12     11
0        Adak          1.18     12
1      Akhiok          1.07      1
1      Akhiok          1.17      2
1      Akhiok          1.08      3
1      Akhiok          1.16      4
1      Akhiok          1.12      5
1      Akhiok          1.11      6
1      Akhiok          1.09      7
1      Akhiok          0.93      8
1      Akhiok          0.98      9
1      Akhiok          1.14     10
1      Akhiok          1.12     11
1      Akhiok          1.12     12
2    Akiachak          0.86      1
2    Akiachak          0.91      2
2    Akiachak          0.92      3
2    Akiachak          0.92      4
2    Akiachak          0.87      5
2    Akiachak          0.88      6
..        ...           ...    ...
272   Wiseman          0.98      7
272   Wiseman          0.98      8
272   Wiseman          0.99      9
272   Wiseman          0.98     10
272   Wiseman          0.92     11
272   Wiseman          1.00     12
273  Wrangell          1.00      1
273  Wrangell          1.00      2
273  Wrangell          1.00      3
273  Wrangell          1.00      4
273  Wrangell          1.00      5
273  Wrangell          1.00      6
273  Wrangell          1.00      7
273  Wrangell          1.00      8
273  Wrangell          1.00      9
273  Wrangell          1.00     10
273  Wrangell          1.01     11
273  Wrangell          1.01     12
274   Yakutat          0.99      1
274   Yakutat          1.00      2
274   Yakutat          1.00      3
274   Yakutat          0.99      4
274   Yakutat          0.98      5
274   Yakutat          0.98      6
274   Yakutat          0.98      7
274   Yakutat          0.98      8
274   Yakutat          0.98      9
274   Yakutat          0.99     10
274   Yakutat          1.00     11
274   Yakutat          0.99     12

[3300 rows x 3 columns]

,City_Name,Solar_1,Solar_2,Solar_3,Solar_4,Solar_5,Solar_6,Solar_7,Solar_8,Solar_9,Solar_10,Solar_11,Solar_12
0,Adak,1.23,1.13,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
1,Akhiok,1.07,1.17,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
2,Akiachak,0.86,0.91,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
3,Akiak,0.88,0.92,0.93,0.93,0.89,0.89,0.90,0.89,0.87,0.84,0.86,0.81
4,Akutan,1.00,1.01,0.99,0.96,1.00,0.91,0.92,0.94,1.04,0.99,1.00,1.05

In [31]:
final_offsets = pd.merge(sorted_offsets, sorted_solar, on=['City_Name', 'month'], how='left')
final_offsets.head()

  City_Name  Temp_offset  month  solar_offset
0      Adak          2.8      1          1.23
1      Adak          3.1      2          1.13
2      Adak          0.5      3          0.87
3      Adak          1.0      4          1.00
4      Adak         -1.3      5          0.95

In [32]:
final_offsets

     City_Name  Temp_offset  month  solar_offset
0         Adak          2.8      1          1.23
1         Adak          3.1      2          1.13
2         Adak          0.5      3          0.87
3         Adak          1.0      4          1.00
4         Adak         -1.3      5          0.95
5         Adak         -1.7      6          0.90
6         Adak         -2.5      7          0.80
7         Adak         -2.6      8          0.90
8         Adak         -0.9      9          1.11
9         Adak          0.7     10          1.21
10        Adak          2.1     11          1.12
11        Adak          3.8     12          1.18
12      Akhiok          0.3      1          1.07
13      Akhiok         -0.1      2          1.17
14      Akhiok         -0.1      3          1.08
15      Akhiok          0.5      4          1.16
16      Akhiok         -0.6      5          1.12
17      Akhiok         -0.1      6          1.11
18      Akhiok         -0.6      7          1.09
19      Akhiok         -1.0      8          0.93
20      Akhiok          0.4      9          0.98
21      Akhiok          0.5     10          1.14
22      Akhiok          0.5     11          1.12
23      Akhiok          1.7     12          1.12
24    Akiachak          0.1      1          0.86
25    Akiachak         -0.1      2          0.91
26    Akiachak         -0.2      3          0.92
27    Akiachak          0.2      4          0.92
28    Akiachak          0.1      5          0.87
29    Akiachak          0.2      6          0.88
...        ...          ...    ...           ...
3270   Wiseman         -2.0      7          0.98
3271   Wiseman         -1.9      8          0.98
3272   Wiseman         -1.6      9          0.99
3273   Wiseman         -0.9     10          0.98
3274   Wiseman          0.8     11          0.92
3275   Wiseman          3.5     12          1.00
3276  Wrangell         -0.6      1          1.00
3277  Wrangell         -0.5      2          1.00
3278  Wrangell         -0.6      3          1.00
3279  Wrangell         -0.6      4          1.00
3280  Wrangell         -0.1      5          1.00
3281  Wrangell          0.2      6          1.00
3282  Wrangell          0.0      7          1.00
3283  Wrangell         -0.1      8          1.00
3284  Wrangell         -0.2      9          1.00
3285  Wrangell         -0.4     10          1.00
3286  Wrangell         -0.6     11          1.01
3287  Wrangell         -0.6     12          1.01
3288   Yakutat          0.1      1          0.99
3289   Yakutat          0.0      2          1.00
3290   Yakutat          0.0      3          1.00
3291   Yakutat         -0.1      4          0.99
3292   Yakutat          0.0      5          0.98
3293   Yakutat         -0.1      6          0.98
3294   Yakutat         -0.2      7          0.98
3295   Yakutat         -0.1      8          0.98
3296   Yakutat          0.0      9          0.98
3297   Yakutat         -0.1     10          0.99
3298   Yakutat          0.0     11          1.00
3299   Yakutat          0.0     12          0.99

[3300 rows x 4 columns]

In [33]:
all_offsets = pd.merge(final_offsets, offsets, on='City_Name', how='left')
all_offsets

,City_Name,Temp_offset,month,solar_offset,ID,Place,Elevation,Latitude,Longitude,Station_Name,...,Solar_3,Solar_4,Solar_5,Solar_6,Solar_7,Solar_8,Solar_9,Solar_10,Solar_11,Solar_12
0,Adak,2.8,1,1.23,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
1,Adak,3.1,2,1.13,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
2,Adak,0.5,3,0.87,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
3,Adak,1.0,4,1.00,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
4,Adak,-1.3,5,0.95,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
5,Adak,-1.7,6,0.90,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
6,Adak,-2.5,7,0.80,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
7,Adak,-2.6,8,0.90,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
8,Adak,-0.9,9,1.11,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
9,Adak,0.7,10,1.21,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
10,Adak,2.1,11,1.12,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
11,Adak,3.8,12,1.18,2,Adak,200,51.848895,-176.635428,DUTCH HARBOR AK US,...,0.87,1.00,0.95,0.90,0.80,0.90,1.11,1.21,1.12,1.18
12,Akhiok,0.3,1,1.07,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
13,Akhiok,-0.1,2,1.17,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
14,Akhiok,-0.1,3,1.08,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
15,Akhiok,0.5,4,1.16,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
16,Akhiok,-0.6,5,1.12,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
17,Akhiok,-0.1,6,1.11,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
18,Akhiok,-0.6,7,1.09,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
19,Akhiok,-1.0,8,0.93,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
20,Akhiok,0.4,9,0.98,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
21,Akhiok,0.5,10,1.14,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
22,Akhiok,0.5,11,1.12,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
23,Akhiok,1.7,12,1.12,283,Akhiok,0,56.944523,-154.171523,KODIAK AIRPORT AK US,...,1.08,1.16,1.12,1.11,1.09,0.93,0.98,1.14,1.12,1.12
24,Akiachak,0.1,1,0.86,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
25,Akiachak,-0.1,2,0.91,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
26,Akiachak,-0.2,3,0.92,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
27,Akiachak,0.2,4,0.92,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
28,Akiachak,0.1,5,0.87,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
29,Akiachak,0.2,6,0.88,84,Akiachak,0,60.910014,-161.424171,BETHEL AIRPORT AK US,...,0.92,0.92,0.87,0.88,0.89,0.87,0.86,0.82,0.85,0.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3270,Wiseman,-2.0,7,0.98,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3271,Wiseman,-1.9,8,0.98,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3272,Wiseman,-1.6,9,0.99,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3273,Wiseman,-0.9,10,0.98,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3274,Wiseman,0.8,11,0.92,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3275,Wiseman,3.5,12,1.00,178,Wiseman,1300,67.411401,-150.121585,BETTLES AIRPORT AK US,...,1.02,1.01,0.97,0.98,0.98,0.98,0.99,0.98,0.92,1.00
3276,Wrangell,-0.6,1,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3277,Wrangell,-0.5,2,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3278,Wrangell,-0.6,3,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3279,Wrangell,-0.6,4,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3280,Wrangell,-0.1,5,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3281,Wrangell,0.2,6,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3282,Wrangell,0.0,7,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3283,Wrangell,-0.1,8,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3284,Wrangell,-0.2,9,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3285,Wrangell,-0.4,10,1.00,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3286,Wrangell,-0.6,11,1.01,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3287,Wrangell,-0.6,12,1.01,202,Wrangell,0,56.420825,-132.352623,WRANGELL AIRPORT AK US,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.01,1.01
3288,Yakutat,0.1,1,0.99,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3289,Yakutat,0.0,2,1.00,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3290,Yakutat,0.0,3,1.00,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3291,Yakutat,-0.1,4,0.99,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3292,Yakutat,0.0,5,0.98,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3293,Yakutat,-0.1,6,0.98,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3294,Yakutat,-0.2,7,0.98,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3295,Yakutat,-0.1,8,0.98,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3296,Yakutat,0.0,9,0.98,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3297,Yakutat,-0.1,10,0.99,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3298,Yakutat,0.0,11,1.00,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99
3299,Yakutat,0.0,12,0.99,193,Yakutat,100,59.546718,-139.728055,YAKUTAT AIRPORT AK US,...,1.00,0.99,0.98,0.98,0.98,0.98,0.98,0.99,1.00,0.99

In [34]:
all_offsets.to_excel('temperature_offsets_formatted.xlsx', sheet_name='offsets')