In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def download_daily_weather(year, month, day):
    
    # For other weather stations, copy and paste daily wunderground html location and then change numbers to "DAY", "MONTH", & "YEAR"
    # Or simply change the weather station name
    url_template = "http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KAKFAIRB57&day={DAY}&month={MONTH}&year={YEAR}&graphspan=day&format=1"
    url = url_template.format(DAY=day, MONTH=month, YEAR=year)
    daily_weather = pd.read_csv(url, header=1)
    daily_weather = daily_weather.rename(columns = {'Time' : 'Temperature F', 
                                                'TemperatureF' : 'Dewpoint F',
                                                    'WindSpeedGustMPH' : 'Humidity %'
                                                }
                                     )
    daily_weather = daily_weather.dropna(axis=0, how='all')
    daily_weather = daily_weather.drop(['DewpointF', 'PressureIn', 'WindDirection', 'WindDirectionDegrees', 'WindSpeedMPH', 
                                    'Humidity', 'HourlyPrecipIn', 'Conditions', 'Clouds', 'dailyrainin', 
                                    'SoftwareType', 'DateUTC<br>'], axis=1)
    return daily_weather

In [3]:
# Make sure year is correct
# Set year manually
year = 2015
jan_data = [download_daily_weather(year, 1, i) for i in range (1, 32)]
jan_weather = pd.concat(jan_data)
jan_weather

                     Temperature F  Dewpoint F  Humidity %
2015-01-01 00:01:00           26.8        25.5          95
2015-01-01 00:11:00           26.8        25.5          95
2015-01-01 00:21:00           26.8        25.5          95
2015-01-01 00:31:00           27.0        25.7          95
2015-01-01 00:41:00           27.0        25.7          95
2015-01-01 00:51:00           27.0        25.7          95
2015-01-01 01:01:00           27.0        25.7          95
2015-01-01 01:11:00           27.0        25.7          95
2015-01-01 01:21:00           27.0        25.7          95
2015-01-01 01:31:00           26.8        25.5          95
2015-01-01 01:41:00           26.8        25.5          95
2015-01-01 01:51:00           26.6        25.4          95
2015-01-01 02:01:00           26.4        25.2          95
2015-01-01 02:11:00           26.2        25.0          95
2015-01-01 02:21:00           26.1        24.8          95
2015-01-01 02:31:00           25.9        24.6          95
2015-01-01 02:41:00           25.9        24.6          95
2015-01-01 02:51:00           25.2        23.9          95
2015-01-01 03:01:00           25.0        23.7          95
2015-01-01 03:11:00           25.0        23.7          95
2015-01-01 07:36:00           23.7        22.5          95
2015-01-01 07:46:00           23.7        22.5          95
2015-01-01 07:56:00           23.7        22.5          95
2015-01-01 10:00:00           19.8        18.3          94
2015-01-01 10:10:00           19.6        18.1          94
2015-01-01 10:20:00           19.4        17.9          94
2015-01-01 10:30:00           19.2        17.8          94
2015-01-01 10:40:00           19.0        17.6          94
2015-01-01 10:50:00           19.0        17.6          94
2015-01-01 11:00:00           19.0        17.6          94
...                            ...         ...         ...
2015-01-31 19:01:00          -16.1       -20.0          82
2015-01-31 19:11:00          -16.2       -20.2          82
2015-01-31 19:21:00          -16.2       -20.2          82
2015-01-31 19:31:00          -16.4       -20.4          82
2015-01-31 19:41:00          -16.4       -20.4          82
2015-01-31 19:51:00          -16.4       -20.4          82
2015-01-31 20:01:00          -16.4       -20.4          82
2015-01-31 20:11:00          -16.6       -20.6          82
2015-01-31 20:21:00          -16.4       -20.4          82
2015-01-31 20:31:00          -16.4       -20.6          81
2015-01-31 20:41:00          -16.4       -20.4          82
2015-01-31 20:51:00          -16.4       -20.4          82
2015-01-31 21:01:00          -16.4       -20.6          81
2015-01-31 21:11:00          -16.4       -20.6          81
2015-01-31 21:21:00          -16.4       -20.6          81
2015-01-31 21:31:00          -16.6       -20.8          81
2015-01-31 21:41:00          -16.6       -20.8          81
2015-01-31 21:51:00          -16.8       -21.0          81
2015-01-31 22:01:00          -17.0       -21.2          81
2015-01-31 22:11:00          -17.0       -21.2          81
2015-01-31 22:21:00          -17.1       -21.3          81
2015-01-31 22:31:00          -17.1       -21.3          81
2015-01-31 22:41:00          -17.3       -21.5          81
2015-01-31 22:51:00          -17.3       -21.5          81
2015-01-31 23:02:00          -17.5       -21.7          81
2015-01-31 23:12:00          -17.7       -21.9          81
2015-01-31 23:22:00          -17.9       -22.0          81
2015-01-31 23:32:00          -17.9       -22.0          81
2015-01-31 23:42:00          -18.0       -22.2          81
2015-01-31 23:52:00          -18.0       -22.2          81

[4144 rows x 3 columns]

In [7]:
#Use this to double check and make sure data looks right.  Make sure to put in a new file name for other stations
jan_weather.to_excel('2015_January_Hourly_Data_KAKFAIR32.xlsx')

In [4]:
feb_data = [download_daily_weather(year, 2, i) for i in range (1, 29)]
feb_weather = pd.concat(feb_data)

mar_data = [download_daily_weather(year, 3, i) for i in range (1, 32)]
mar_weather = pd.concat(mar_data)

apr_data = [download_daily_weather(year, 4, i) for i in range (1, 31)]
apr_weather = pd.concat(apr_data)

may_data = [download_daily_weather(year, 5, i) for i in range (1, 32)]
may_weather = pd.concat(may_data)

jun_data = [download_daily_weather(year, 6, i) for i in range (1, 31)]
jun_weather = pd.concat(jun_data)

jul_data = [download_daily_weather(year, 7, i) for i in range (1, 32)]
jul_weather = pd.concat(jul_data)

aug_data = [download_daily_weather(year, 8, i) for i in range (1, 32)]
aug_weather = pd.concat(aug_data)

sep_data = [download_daily_weather(year, 9, i) for i in range (1, 31)]
sep_weather = pd.concat(sep_data)

oct_data = [download_daily_weather(year, 10, i) for i in range (1, 32)]
oct_weather = pd.concat(oct_data)

nov_data = [download_daily_weather(year, 11, i) for i in range (1, 31)]
nov_weather = pd.concat(nov_data)

dec_data = [download_daily_weather(year, 12, i) for i in range (1, 32)]
dec_weather = pd.concat(dec_data)

In [5]:
df_list = [jan_weather, feb_weather, mar_weather, apr_weather, may_weather, jun_weather, jul_weather, aug_weather, sep_weather, 
           oct_weather, nov_weather, dec_weather]

year_weather = pd.concat(df_list)

In [6]:
# Remove missing data
mask = year_weather['Temperature F'] > -999
year_weather = year_weather[mask]

In [7]:
# Make sure to put in a new file name
year_weather.to_excel('2015_Annual_Hourly_Weather_KAKFAIRb57.xlsx')